In [2]:
import numpy as np

x = np.arange(10)
y = x ** 2
z = 2 * x
a = x @ np.transpose(x)
print(x)
print(y)
print(z)
print(a, type(a))

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
[ 0  2  4  6  8 10 12 14 16 18]
285 <class 'numpy.int64'>


In [3]:
np.savez("x_y-squared.npz", x_axis=x, y_axis=y)

In [4]:
%whos
del x,y
%whos

Variable   Type       Data/Info
-------------------------------
a          int64      285
np         module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
x          ndarray    10: 10 elems, type `int64`, 80 bytes
y          ndarray    10: 10 elems, type `int64`, 80 bytes
z          ndarray    10: 10 elems, type `int64`, 80 bytes
Variable   Type       Data/Info
-------------------------------
a          int64      285
np         module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
z          ndarray    10: 10 elems, type `int64`, 80 bytes


In [16]:
load_xy = np.load("x_y-squared.npz")

print(load_xy.files)
%whos

['x_axis', 'y_axis']
Variable    Type       Data/Info
--------------------------------
a           int64      285
array_out   ndarray    10x2: 20 elems, type `int64`, 160 bytes
load_xy     NpzFile    NpzFile 'x_y-squared.npz'<...>with keys: x_axis, y_axis
np          module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
x           ndarray    10: 10 elems, type `float64`, 80 bytes
y           ndarray    10: 10 elems, type `float64`, 80 bytes
z           ndarray    10: 10 elems, type `int64`, 80 bytes


In [17]:
x = load_xy["x_axis"]
y = load_xy["y_axis"]
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
3


Python dictionaries are indexed by keys, which can be any immutable type; strings and numbers can always be keys.
```
urban_dictionary = {}
urban_dictionary['bet'] = 'for sure or okay'
```

In [19]:
print(load_xy["x_axis"])
print(load_xy["x_axis"][3])

[0 1 2 3 4 5 6 7 8 9]
3


In [7]:
array_out = np.block([x[:, np.newaxis], y[:, np.newaxis]])
print("the output array has shape ", array_out.shape, " with values:")
print(array_out)

the output array has shape  (10, 2)  with values:
[[ 0  0]
 [ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]
 [ 6 36]
 [ 7 49]
 [ 8 64]
 [ 9 81]]


In [9]:
np.savetxt("x_y-squared.csv", X=array_out, header="x, y", delimiter=",")
del x, y
load_xy = np.loadtxt("x_y-squared.csv", delimiter=",")
x = load_xy[:, 0]
y = load_xy[:, 1]
print(x)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [14]:
z = load_xy["x_axis"]


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices